### PR TITLE
[WIP] Redesigned Landing-Page

### PR DESCRIPTION
**Pull request by webdesserts**
This is a work in-progress. I am using the landing page to get the basics of how we're going to organize our css figured out. Currently only has the "Getting Started" section decently put together. Very Bare-bones right now.

### CODE REVIEW

**Comment by brotzky** [comment]
Nice, will double check this tonight after work.

**Comment by webdesserts** [comment]
@brotzky Ahh, this wasn't quite ready for merge yet. I was running into bugs/issues and mostly published this so @mxstbr and @oliverturner could play around with the code.

**Comment by brotzky** [comment]
Sorry! Fairly new to this process. Will learn...

**Comment by webdesserts** [comment]
@brotzky As am I 😊. I don't think it's any harm done as we aren't publishing anytime soon.

It probably doesn't help that we've been having the majority of our conversations on gitter. Probably been leaving you out of the loop. I'll try to use github issues/prs a bit more in the future so discussions are a bit easier to keep track of. Also I think a bit **do not merge** will help next time as well (see that pretty commonly in other repos).

@mxstbr should we just leave this PR as is or revert it? I can always start another PR.

**Comment by mxstbr** [comment]
It's fine, I need @brotzky to give me access to the domain anyway, until then I can't point it towards the server

**Comment by brotzky** [comment]
Added to domain manager on namecheap @mxstbr. Point it where you like.

**Pull request merged**
