### PR TITLE
[WIP] Redesigned Landing-Page (continued)

### PR DESCRIPTION
**Pull request by webdesserts**
## Not Ready For Merge

This is a work-in-progress branch that contains progress for the Landing Page on #3 and is a continuation of #5. Feel free leave any feedback as I'm going.

**Current Progress**:
- [x] Basic Scaffolding
- [ ] Responsive
- [ ] Functioning Links
- [ ] Icons
- [ ] Spiffy Header
- [ ] Logo

### CODE REVIEW

**Comment by brotzky** [comment]
Nice work @webdesserts. I learned some little things from looking through the commit. 

I would suggest writing imported components like this: ```import Button from './Button';```. I think it's more clear to readers that way. Let me know you thoughts.

**Comment by webdesserts** [comment]
@brotzky If I did rewrite those routes it would be more like `import Button from '../../components/Button'`. I think this is one of those magic routes that is set up in webpack within the boilerplate. I actually agree and am not a huge fan of these types of magic routes. I would much rather set a "root" directory and see something like `/components/Button`. Unfortunately both of those approaches have issues with current Editors/IDEs :(

**Comment by brotzky** [comment]
Nice, that's completely fair.

**Comment by mxstbr** [comment]
Webpack is configured to automatically search the components, container, selectors and saga folders, but we can change that to only search in the root app directory so you'd `import Button from 'components/Button';`. Would that be clearer?

**Comment by webdesserts** [comment]
@mxstbr I think that would be better. The main concern I have is that at a glance `import Button from 'Button'` seems like a normal module import (though I assume the capital letter is a distinguishing factor). I think adding the extra folder up would give the users some context and possibly prevent naming conflicts between the other folders as well, without burdening devs too much?

**Pull request closed without merging**
